### ISSUE TITLE
Broken Bootstrap Address: router.silotis.us

### ISSUE THREAD

**Issue by AlhasanIQ** [anacrolix/dht#18]
The address `router.silotis.us` is broken and throwing errors since its dns is not working

The of this server have mentioned that it is temporary previously [here](https://sourceforge.net/p/libtorrent/mailman/message/35041235/)

Please confirm the issue from your side so that i could create a PR to fix.

**Comment by AlhasanIQ** [comment]
The host is back up for me and the AAAA record is being resolved perfectly (could be an ISP cache corruption or a faulty from the host's side).

I still think the host is obsolete and should not be relied on.

router.bittorrent.com is the one.

**Comment by anacrolix** [comment]
I'll leave it in there until circumstances change.
