### ISSUE TITLE
Ability to multiplex connection

### ISSUE THREAD

**Issue by cretz** [anacrolix/dht#2]
Pardon my naivete of the bittorrent protocol, but is it possible currently to multiplex the connection? I see I can probably provide my own socket and pre-obtain a byte array and pass it along only if it's bencoded. Is this the recommended approach or might it be preferred to have a config option to handle fallthrough packets?

**Comment by anacrolix** [comment]
Yes. This is done in github.com/anacrolix/torrent the other way around. A uTP socket is created on UDP, and packets that aren't consumed by uTP are exposed as a net.PacketConn that is passed to anacrolix/dht. See torrent.NewClient, dht.ServerConfig, and anacrolix/utp.Socket.

**Comment by cretz** [comment]
Thanks! (closing as this is not really an issue)
