### ISSUE TITLE
Seems to find peers very slowly compared to webtorrent/torrent-discovery

### ISSUE THREAD

**Issue by bsuh** [anacrolix/dht#23]
Only using DHT to find peers, https://github.com/webtorrent/torrent-discovery (through peerflix) connects to ~20 peers instantly while this package (through confluence) connects to 1 peer in 20 seconds.

I have some packet captures.
[packet-capture.zip](https://github.com/anacrolix/dht/files/2130325/packet-capture.zip)

**Comment by bsuh** [comment]
Additional context. Host machine is OS X. peerflix and confluence running inside Docker containers. confluence running on OS X seems to find peers very well.

After looking at the packet captures (I thought they would be too opaque for me to understand at first), it seems that the problem is just for some reason the TCP connection establishing packets aren't being ACK'd. Why would that be a problem for confluence but not peerflix?

**Comment by bsuh** [comment]
Based on additional tests on Linux host (VM I provisioned from a hosting provider) running confluence, confluence in Docker, confluence + openvpn in Docker, this seems to be a Docker + some distinct way that the socket is set up that is causing problems.

**Comment by anacrolix** [comment]
It's possibly related to #24, could you try with the fix for that, https://github.com/anacrolix/dht/commit/efcc29278754bdd5e766edfb6675f3fe0199fc6f?

**Comment by bsuh** [comment]
Seems to be fixed!
