### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by nenadstojanovikj** [anacrolix/dht#28]
Since adding a new parameter in the `s.config.ConnectionTracking.Wait` breaks the backwards compatibility, I can no longer use `anacrolix/torrent` through with `go mod`. 

I'm getting the following issue when I run `go get -u`
```
# github.com/anacrolix/dht
../../../../pkg/mod/github.com/anacrolix/dht@v1.0.1-0.20190118110415-9a2d88b4a294/server.go:623:44: not enough arguments in call to s.config.ConnectionTracking.Wait
	have (conntrack.Entry, string, number)
	want (context.Context, conntrack.Entry, string, conntrack.priority)

```

I think this can be fixed by simply creating a new Github release. Thanks.

**Comment by anacrolix** [comment]
Thanks for reporting this.

**Comment by anacrolix** [comment]
I've released several new versions to fix this. Let me know if you have any more issues.

**Comment by nenadstojanovikj** [comment]
Thanks, this fixed `go get -u` for me!
