### ISSUE TITLE
Does DHT work standalone?

### ISSUE THREAD

**Issue by asim** [anacrolix/dht#3]
Hey, I've been trying to get this library to work standalone without bootstrapping from the global servers but I seem to not be getting the expected behaviour. 

Here's a gist which sets up a server standalone https://gist.github.com/asim/99d9978f76ec46083b6dcf4a65b58cb5 and then the equivalent can be run with ports changed and using the first address in BootstrapNodes list. 

When I run this locally or across the public internet I can see udp packets flowing back and forth between the servers but nothing is ever announced and I can't actually tell if anything's working.

If I use the global servers then it all seems to work fine. Any ideas why this won't bootstrap as a standalone dht server?

**Comment by anacrolix** [comment]
Are you adding the first address as a localhost address? Try with `NoSecurity: true` in your `ServerConfig`.

**Comment by asim** [comment]
Tried with NoSecurity: true but no change. Do you have a working example of dht without global servers?

**Comment by anacrolix** [comment]
Honestly I haven't tested it myself. Several users use/used it with their own private DHT network, here are relevant issues from before I moved dht from anacrolix/torrent. https://github.com/anacrolix/torrent/issues?utf8=%E2%9C%93&q=dht%20bootstrap. You might mine those or other old DHT issues from that repo for info, or ask those users about their experiences.

Let me know if you don't find anything useful there and I'll run your examples in a few days.

**Comment by asim** [comment]
I haven't found anything. It would be helpful if you could test whether this actually works without global servers considering you provide the option.

**Comment by anacrolix** [comment]
You can now provide your own StartingAddrs, the implementation will now never attempt to use the global network by default. See http://godoc.org/github.com/anacrolix/dht#ServerConfig. Let me know how it goes for you.
