### ISSUE TITLE
error in Marshaling krpc.id

### ISSUE THREAD

**Issue by Fluturenet** [anacrolix/dht#30]
```
func main() {
	var id krpc.ID
        copy(id[:],[]byte("012345678901234567890"))
        fmt.Printf("%s",bencode.MustMarshal(id))
}
```
I receive:
li48ei49ei50ei51ei52ei53ei54ei55ei56ei57ei48ei49ei50ei51ei52ei53ei54ei55ei56ei57ee

Shouldn't be:
20:012345678901234567890

Michele

**Comment by anacrolix** [comment]
Yes, thanks, good catch.
