### ISSUE TITLE
krpc.CompactIPv4NodeAddrs.MarshalBinary() does not produce compact IPv4 form

### ISSUE THREAD

**Issue by yarikk** [anacrolix/dht#33]
krpc.CompactIPv4NodeAddrs (or NodeAddr) does not have the essential To4() piece in its marshaller functions, unlike pp.CompactIp which does.
Without this, the use sites need to carry the conversion explicitly.

**Comment by anacrolix** [comment]
Thanks @yarikk . Are you using this externally for something? `krpc.CompactIPv4NodeAddrs.MarshalBinary` calls into https://github.com/anacrolix/dht/blob/70d5c883ca52ff4e1bd27116f3f73d76d9d8dce6/krpc/compact_helpers.go#L54 which checks that each element marshals to 6 bytes, so while the users would need to check they're inserting 4-byte `net.IP`s, anything else would cause a panic. Are there any specific areas where you think IPv6 `net.IP`s are being used?

**Comment by anacrolix** [comment]
Sorry I missed your [mention](https://gitter.im/anacrolix/torrent?at=5e8490e4987a3333241d0d7d) of PEX implementation. Isn't it necessary to separate peer addresses into IPv4 and IPv6 anyway there?

**Comment by yarikk** [comment]
https://play.golang.org/p/GbwYj3eG13m

**Comment by anacrolix** [comment]
I understand, but my questions hold.

**Comment by yarikk** [comment]
I'm not sure I understand the questions. Neither if the panic is the best approach here.

Every time an occasional reader bumps into a block like this in a random place, one surely wonders why is it there:

```
 	ip := ipport.IP
 	if ip4 := ip.To4(); ip4 != nil && len(ip) != net.IPv4len {
 		ip = ip4
 	}
 	…
```

The answer, far from being instantly obvious, are only there to facilitate binary marshallers, and therefore should be internal to the marshallers instead of pushing the internal details onto the callers up stack. An example of done right is  peer_protocol.CompactIp in anacrolix/torrent where the marshaller does the conversion if needed.

Feels like the change could be fairly easy and harmless.

**Comment by anacrolix** [comment]
It might help if I see where you intend to use this. For now consider that the contract of `krpc.CompactIPv4NodeAddrs` is to marshal 4-byte `net.IP`s and nothing else.

**Comment by yarikk** [comment]
E.g. https://github.com/anacrolix/torrent/blob/48bea90f0a1fc5068e9929b8cc673d3be14f9e41/pex.go#L47 is there solely because of this.

**Comment by anacrolix** [comment]
To my understanding, just because an IPv6 address can be reduced to an IPv4 one, doesn't mean that you necessarily have to connect to it over the IPv4 protocol. It might be that you connected to that peer over IPv6, and so want to transmit that address as a valid IPv6 address.

**Comment by yarikk** [comment]
Yeah, what I'm suggesting isn't about choosing which field for an address to go – that's fine, sort of. I mean, at the marshalling site, the code should not assume the minimal 32-bit representation of the address and should try to obtain one instead of panicking when the assumption doesn't hold.

**Comment by anacrolix** [comment]
What if the IPv4/IPv6 state was in `pexEvent` (and conversion occurred there). Further, what if `pexEvent.addr` was converted in to a `NodeAddr` in advance. Converting it in the `pexMsgFactory` on demand has a noticeable overhead. We could leave out a lot of this Compact~ stuff until generics is available, then we can bake in our assumptions in the types with less guesswork?

**Comment by yarikk** [comment]
> What if the IPv4/IPv6 state was in pexEvent (and conversion occurred there) …

@anacrolix, thanks for getting back to me on this.

I think the conversion – if it has to happen – should be done at the place where a need for such conversion is created: in the marshaller. This not only completes the abstraction of the on-wire representation from the rest of the program but also creates opportunities for local optimisation. For example, further along, the marshaler may do the conversion conditionally (say, when Len != 4) or be smarter about the 16-byte view of the IPv4 and extract the 4-byte slice directly, without copying. Pushing the problem upper on stack is suboptimal.

**Comment by anacrolix** [comment]
My reading of the PEX BEP is that whether a peer is "6" or otherwise would depend on its connectivity in the Client. I understand it's plausible to connect over IPv6 to an IPv4 address, and have the peer in "added6". If that's the case, the decision is made at a level above PEX, it should try to stuff addresses wherever it can. Have I read that wrong? Thanks for your patience on this. There is an ipv6 method somewhere on PeerConn that can be used to discriminate this at the point the peer is added to the PEX log.

**Comment by yarikk** [comment]
> Further, what if pexEvent.addr was converted in to a NodeAddr in advance.

It could, yes, although wouldn't change much there: we'd still want the near-wire snapshot of the entire PexMsg cached. The underlying representation of IP in NodeAddr would still remain agnostic to what happens further down with it – until the marshaller chokes.

**Comment by yarikk** [comment]
> My reading of the PEX BEP is that whether a peer is "6" or otherwise would depend on its connectivity in the Client …

Uhm… the BEP does mention the address families but mainly for the purpose of differentiating the syntax of on-wire representation of the addresses — I don't think it is meant to convey the information about the actual stack over which the connection was made. If it were – well, we'd need to track `Network` along with `IP` in NodeAddr.

**Comment by anacrolix** [comment]
That's a good point. The overlap of IPv4-in-IPv6 is probably small enough most clients would just try both or just favour one at their discretion too.

**Comment by anacrolix** [comment]
This client for example defers to the network stack by default, but if different dialers are provided for ipv6 and ipv4, it will try both for all addresses.

**Comment by yarikk** [comment]
> The addresses should already be correct for the type they're being marshalled into (mine), and they should coerced (yours)

Not quite: you see, the suggestion is to update the IPv4 marshaller – that is, the decision on which list to put an address on is already made by the application. We do not re-qualify the list (nor do we coerce the both lists). No extra "gravity" created.

**Comment by yarikk** [comment]
@anacrolix thanks for accepting the proposal – much appreciated!

Do you think you could assign a version tag (cut a release) from _master_ any time soon?
