### ISSUE TITLE
Server::findNode not exposed?

### ISSUE THREAD

**Issue by cndolo** [anacrolix/dht#34]
Hi.
First of all, thank you for the great work you have done on this project.

I just discovered this repo a few days ago and would like to continue using it for a project.
For that I would need to send `find_node` queries to target addresses. 
Is it possible that the `findNode` function in `server.go` is not exposed unlike `Ping` and `Announce`?
If so, how can one use the function after having bootstrapped?
I just started using go a few days ago, therefore, this may be an oversight on my part.

Thank you,
Charmaine

**Comment by anacrolix** [comment]
Hi Charmaine,

find_node and get_peers are not publicly exposed. This is just because I've not had the need, there's no reason they couldn't be. Generally find_node is used iteratively from a bootstrap, and get_peers from an announce.

If you could give more information on how you will use find_node, I could determine the best way to expose it as a method, or you can submit a PR to do it yourself.

**Comment by cndolo** [comment]
Hi Matt,

Thank you for your response.
> If you could give more information on how you will use find_node, I could determine the best way to expose it as a method

Sure, I would like to use find_node after bootsrapping.
In particular, I want to iteratively send a bunch of find_node queries to the already known nodes and use their responses (i.e. the k nodes I get back) to send more find_node queries to.

**Comment by anacrolix** [comment]
You may want to make use of the traversal logic if you are trying to locate a particular node. That said, the single query method itself is still useful exposed alone.

**Comment by cndolo** [comment]
> You may want to make use of the traversal logic if you are trying to locate a particular node.

Not really, my goal is to crawl the DHT.

> That said, the single query method itself is still useful exposed alone.

May I ask which method you are referring to? Server::query()? Possibly not because it is not exposed..

**Comment by anacrolix** [comment]
I've started a [branch](https://github.com/anacrolix/dht/tree/expose-query) to expose some methods. Would you make use of the rate-limiting in the Server, or manage that externally?

**Comment by cndolo** [comment]
Thank you!
Definitely. If I can handle the rate-limiting internally, I would prefer to do so.

**Comment by anacrolix** [comment]
Server.FindNode, GetPeers, and Query are exposed in v2.8.0. Let me know how those go for you.

**Comment by cndolo** [comment]
Thanks Matt - I will keep you posted as soon as there is something I think you may be interested in.
