### ISSUE TITLE
Does int160 need to be exposed?

### ISSUE THREAD

**Issue by cndolo** [anacrolix/dht#35]
Hi,

Just a thought, potentially wrong.
Does `int160` need to exposed in order to use the `Server::FindNode` function?

**Comment by anacrolix** [comment]
Yes! I just implemented this in `master` yesterday purely by coincidence. See https://github.com/anacrolix/dht/commit/d5abdc171fa5647d06731c91d5d840da5ccdd10e. Thanks!
