### ISSUE TITLE
does it generate a lot of trafic ?

### ISSUE THREAD

**Issue by mh-cbon** [anacrolix/dht#6]
Hi,

Using this server init, and two working nodes on 9090 / 9091 ports.

```go

func getDhtTable(since int, bootstrap []string, refresh time.Duration) (ret *dht.Server, port int, err error) {
	err = errors.New("No port found.")
	for i := since; i < since+30; i++ {
		conf := &dht.ServerConfig{
			Addr:               fmt.Sprintf("localhost:%v", i),
			NoDefaultBootstrap: !true,
			NoSecurity:         true,
			BootstrapNodes:     bootstrap,
			StoreTimeout:       refresh,
			OnQuery: func(query *krpc.Msg, source net.Addr) (propagate bool) {
				log.Printf("query %v %#v\n", source, query.Q)
				<-time.After(1 * time.Second)
				return true // true or false ? unclear doc.
			},
			OnResponsePeer: func(query krpc.Msg, source dht.Addr) {
				r := ""
				if query.R != nil {
					r = fmt.Sprintf("ret.V=%#v ret.Seq=%#v ret.K=%#v ret.Sign=%#v",
						query.R.V, query.R.Seq, query.R.K, query.R.Sign)
				}
				log.Printf("response %v err=%v %v\n", source, query.Error(), r)
			},
		}

		if srv, netErr := dht.NewServer(conf); netErr == nil {
			ret = srv
			port = i
			err = nil
			break
		}
	}
	return
}
```

In the OnQuery, i had to add a 1s timeout rate limiter, otherwise the table would generate a loooottttt of traffic.
A quick count with grep/wc yields ~~2860~~ 5500 query per second here (so if i have two nodes, its like ~~5k~~ 10k :o).

Is there anything to take care of here, as i suspected, or it s expected to be that fast under best conditions ?

The under best conditions matters, as the phenomena won t happen if any of the node is offline (it creates a sort of 10 sec blocking timeout in the stream).

thanks!

**Comment by anacrolix** [comment]
Yeah I have a node in production 24/7, and it gets insane traffic.

**Comment by anacrolix** [comment]
Here's some numbers and it's only been up 2 days:
"dhtAnnounceErrors": 0,
"dhtQueryBad": 0,
"dhtRead": 26869142,
"dhtReadAnnouncePeer": 425178,
"dhtReadBlocked": 1687833,
"dhtReadInvalidToken": 28014,
"dhtReadNotKRPCDict": 59550,
"dhtReadQuery": 23529738,
"dhtReadUnmarshalError": 376,
"dhtReadZeroPort": 169,
"dhtWriteErrors": 127,
"dhtWrites": 27455503,
DHT announces: 543818

**Comment by anacrolix** [comment]
I've recently made some big changes to this package, you may wan to try again. Also have you tried running with `ServerConfig{Passive: true}`, a lot of the traffic you're seeing is likely responding to queries from other nodes, a lot of nodes choose not to do this. Also I don't think you should sleep in the OnQuery callback, you will lock the entire Server. Another approach would be better.

**Comment by anacrolix** [comment]
The amount of traffic should now be significantly reduced.
