### ISSUE TITLE
Trouble cloning the repository

### ISSUE THREAD

**Issue by nochso** [anacrolix/dht#8]
A simple `git clone` is taking ages:

```
$ git clone git@github.com:anacrolix/dht.git
Cloning into 'dht'...
remote: Counting objects: 218641, done.
remote: Compressing objects: 100% (6/6), done.
Receiving objects:  13% (30228/218641), 20.12 MiB | 39.00 KiB/s
```
Same problem when cloning a fork of this repository. I've tried both HTTPS and SSH. Downloading the ZIP works fine and it's tiny.

Do you have any idea what's going on? Any other repo is working fine.

**Comment by anacrolix** [comment]
I have the same problem on my machine. The git objects are huge. I'll try to track it down, it may be a relic of when I separated this from anacrolix/torrent. Thank you for reporting.

**Comment by anacrolix** [comment]
I've fixed this, I had some tags get leaked in from another project.
```
$ git clone git@github.com:anacrolix/dht.git
Cloning into 'dht'...
remote: Counting objects: 693, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 693 (delta 0), reused 2 (delta 0), pack-reused 686
Receiving objects: 100% (693/693), 247.94 KiB | 0 bytes/s, done.
Resolving deltas: 100% (420/420), done.
```

**Comment by nochso** [comment]
Thanks! Maybe now `dep init` will work :)
